
name: GitHub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  CONTAINER_IMAGE: https://ghcr.io/$GITHUB_ACTOR/$GITHUB_REF_NAME:latest
    # https://ghcr.io/ is the container registry
    # GITHUB_ACTOR is the user who initiated the workflow
    # GITHUB_REF_NAME is the branch/tag that initiated the workflow
    # :latest specifies the most recent version (duh)
    
## CI/CD Service definition -> More Requirements for Docker in Docker
#services:
  #- name: docker:dind
    #entrypoint: ["env", "-u", "DOCKER_HOST"]
    #command: ["dockerd-entrypoint.sh"]

jobs:

  #build:

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v3
    #- name: Pre-check that Docker is installed
      #run: docker version
    ##- name: Build the Docker image
      ##run: docker build . --file Dockerfile --tag https://ghcr.io/$GITHUB_ACTOR/$GITHUB_REF_NAME:latest
    #- name: Build the Docker image
      #run: docker build --pull https://ghcr.io/$GITHUB_ACTOR/$GITHUB_REF_NAME:latest .
    #- name: Push the Docker image
      #run: docker push https://ghcr.io/$GITHUB_ACTOR/$GITHUB_REF_NAME:latest  


  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
      with:
        ruby-version: 2.6.6

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "
        

  deploy:
    runs-on: ubuntu-latest
    
    env:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_PRODUCTION_KEY: ${{ secrets.HEROKU_PRODUCTION_KEY }}
    
    steps:
      - run: apk add ruby-dev # dpl needs ruby
      run: apk add git # container doesn't have git for some reason
      run: apk add curl # or curl?!?
      run: gem install json_pure # another dumb error message removed by this line
      run: gem install faraday -v 1.8.0 # this is getting old.
      run: gem install dpl # this is the only line in the docs
      run: gem install dpl-heroku # another one for fun
      run: dpl --provider=heroku --app=env.HEROKU_APP_NAME --api-key=env.HEROKU_PRODUCTION_KEY

